language: python
python:
  - "2.7"
# command to run tests
script:
  - python -m unittest discover -s phylotoast/test/ -p test_biom_calc.py -v
  - python -m unittest discover -s phylotoast/test/ -p test_util.py -v
# command for email notifications, set to no notifications via email
notifications:
    email: false
